"""Render BearCase as readable markdown."""
from __future__ import annotations

from ..schemas import BearCase


def render(b: BearCase) -> str:
    dt = f"${b.downside_target_6m_usd:,.2f}" if b.downside_target_6m_usd else "n/a"
    downside = f"{b.downside_pct:+.1f}%" if b.downside_pct is not None else "n/a"

    lines: list[str] = [
        f"# Bear Researcher — {b.symbol}",
        "",
        f"_Analysis date: {b.as_of_date}_",
        "",
        f"**Conviction (self-rated):** {b.conviction_self_rated}/10",
        f"**6-month downside target:** {dt}  ({downside})",
        "",
        "## The Bear Case",
        "",
        "### 1. Business quality concerns",
        "",
        b.business_quality_concerns,
        "",
        "### 2. Momentum skepticism",
        "",
        b.momentum_skepticism,
        "",
        "### 3. Catalyst counter",
        "",
        b.catalyst_counter,
        "",
        "### 4. Valuation concerns",
        "",
        b.valuation_concerns,
        "",
        "## Self-assessment",
        "",
        f"> **Strongest point:** {b.strongest_point}",
        "",
        f"> **Biggest weakness (what the Bull will attack):** {b.biggest_weakness}",
        "",
        "---",
        "",
        "_Generated by the Bear Researcher (Claude Sonnet)._",
        "",
    ]
    return "\n".join(lines)
