"""Render BullCase as readable markdown."""
from __future__ import annotations

from ..schemas import BullCase


def render(b: BullCase) -> str:
    pt = f"${b.price_target_6m_usd:,.2f}" if b.price_target_6m_usd else "n/a"
    upside = f"{b.upside_pct:+.1f}%" if b.upside_pct is not None else "n/a"

    lines: list[str] = [
        f"# Bull Researcher — {b.symbol}",
        "",
        f"_Analysis date: {b.as_of_date}_",
        "",
        f"**Conviction (self-rated):** {b.conviction_self_rated}/10",
        f"**6-month price target:** {pt}  ({upside})",
        "",
        "## The Bull Case",
        "",
        "### 1. Business quality",
        "",
        b.business_quality,
        "",
        "### 2. Momentum validity",
        "",
        b.momentum_validity,
        "",
        "### 3. Catalyst",
        "",
        b.catalyst,
        "",
        "### 4. Valuation context",
        "",
        b.valuation_context,
        "",
        "## Self-assessment",
        "",
        f"> **Strongest point:** {b.strongest_point}",
        "",
        f"> **Biggest vulnerability (what the Bear will attack):** {b.biggest_vulnerability}",
        "",
        "---",
        "",
        "_Generated by the Bull Researcher (Claude Sonnet)._",
        "",
    ]
    return "\n".join(lines)
