"""Render ExitConfirmation as readable markdown."""
from __future__ import annotations

from ..schemas import ExitConfirmation


def render(c: ExitConfirmation) -> str:
    verdict_emoji = {
        "CONFIRM_EXIT": "✅ CONFIRM EXIT",
        "DOWNGRADE_TO_WATCH": "⚠ DOWNGRADE → WATCH",
        "HOLD": "🟢 HOLD (override)",
    }.get(c.verdict, c.verdict)

    lines = [
        f"# Exit Confirmer — {c.symbol} ({c.as_of_date})",
        "",
        f"## {verdict_emoji}",
        "",
        f"- **Urgency:** {c.urgency}",
        "",
        "## Reasoning",
        "",
        c.exit_reasoning,
        "",
        "## Lesson for memory",
        "",
        f"> {c.lesson_for_memory}",
        "",
        "---",
        "",
        "_Generated by the Exit Confirmer (Claude Sonnet)._",
        "",
    ]
    return "\n".join(lines)
