"""Render a FundamentalReport as a human-readable markdown file."""
from __future__ import annotations

from ..schemas import FundamentalReport


def render(report: FundamentalReport) -> str:
    r = report

    lines: list[str] = [
        f"# Fundamental Analyst — {r.symbol}",
        "",
        f"_Analysis date: {r.as_of_date}_",
        "",
        "## Verdict",
        "",
        f"**Fundamental Score:** {r.fundamental_score}/10",
        "",
        "## Growth Quality",
        "",
        f"- **Revenue trend:** {r.growth_quality.revenue_trend}",
        f"- **Margin trend:** {r.growth_quality.margin_trend}",
        f"- **FCF conversion:** {r.growth_quality.fcf_conversion}",
        f"- **EPS acceleration:** {r.growth_quality.eps_acceleration}",
        "",
        "## Valuation",
        "",
        f"- **P/E vs sector:** {r.valuation_assessment.pe_vs_sector}",
        f"- **Justified:** {'yes' if r.valuation_assessment.justified else 'no'}",
        "",
        f"> {r.valuation_assessment.justification}",
        "",
        "## Key Drivers",
        "",
        f"**Upside:** {r.key_upside_driver}",
        "",
        f"**Downside risk:** {r.key_downside_risk}",
        "",
    ]

    if r.earnings_risk_days is not None:
        if r.earnings_risk_days >= 0:
            lines += [f"**Next earnings:** in {r.earnings_risk_days} days", ""]
        else:
            lines += [
                f"**Last earnings:** {abs(r.earnings_risk_days)} days ago (next not yet scheduled)",
                "",
            ]

    if r.red_flags:
        lines += ["## Red Flags", ""]
        for flag in r.red_flags:
            lines += [f"- **[{flag.category}]** {flag.detail}"]
        lines += [""]

    lines += [
        "## Summary",
        "",
        r.summary,
        "",
        "---",
        "",
        "_Generated by the Fundamental Analyst agent._",
        "",
    ]
    return "\n".join(lines)
