"""Render InstitutionalFlowReport as readable markdown."""
from __future__ import annotations

from ..schemas import InstitutionalFlowReport, TopHolder


def render(r: InstitutionalFlowReport) -> str:
    lines = [
        f"# Institutional Flow — {r.symbol}",
        "",
        f"_Analysis date: {r.as_of_date}_",
        "",
        f"**Smart-money score:** {r.smart_money_score}/10 — {r.smart_money_direction}",
        "",
        "## 13F Snapshot",
        "",
    ]
    if r.inst_ownership_pct is not None:
        lines.append(f"- **Institutional ownership:** ~{r.inst_ownership_pct:.1f}% of float")
    if r.new_institutional_positions_count is not None:
        lines.append(f"- **New positions opened (last Q):** {r.new_institutional_positions_count}")
    if r.exited_institutional_positions_count is not None:
        lines.append(f"- **Positions fully exited (last Q):** {r.exited_institutional_positions_count}")
    lines += ["", "### Top 5 holders", ""]
    for h in r.top_5_holders:
        lines.append(_holder_line(h))
    if r.biggest_buyers_qoq:
        lines += ["", "### Biggest buyers (Q-o-Q)", ""]
        for h in r.biggest_buyers_qoq:
            lines.append(_holder_line(h))
    if r.biggest_sellers_qoq:
        lines += ["", "### Biggest sellers (Q-o-Q)", ""]
        for h in r.biggest_sellers_qoq:
            lines.append(_holder_line(h))

    lines += [
        "",
        "## Dark Pool",
        "",
        f"- **Trend:** {r.dark_pool_trend}",
    ]
    if r.dark_pool_30d_notional_usd is not None:
        lines.append(f"- **30-day notional:** ${r.dark_pool_30d_notional_usd:,.0f}")
    if r.dark_pool_pct_of_volume is not None:
        lines.append(f"- **% of dollar volume (last 30d):** {r.dark_pool_pct_of_volume:.1f}%")

    lines += [
        "",
        "## Options Flow",
        "",
        f"- **Sentiment:** {r.options_flow_sentiment}",
    ]
    if r.options_flow_call_put_premium_ratio is not None:
        lines.append(
            f"- **Call/Put premium ratio (5d):** {r.options_flow_call_put_premium_ratio:.2f}x"
        )
    if r.biggest_uoa_prints:
        lines += ["", "**Biggest UOA prints:**"]
        for p in r.biggest_uoa_prints:
            lines.append(f"- {p}")

    lines += [
        "",
        "## Insider Activity (30d)",
        "",
        f"- **Signal:** {r.insider_30d_signal}",
    ]
    if r.insider_30d_net_notional_usd is not None:
        sign = "+" if r.insider_30d_net_notional_usd >= 0 else ""
        lines.append(
            f"- **Net insider notional (30d):** {sign}${r.insider_30d_net_notional_usd:,.0f}"
        )

    lines += [
        "",
        "## Convergence",
        "",
        r.convergence_notes,
        "",
        "## Summary",
        "",
        r.summary,
        "",
        "---",
        "",
        "_Generated by the Institutional Flow agent (Gemini Flash) — Unusual Whales data._",
        "",
    ]
    return "\n".join(lines)


def _holder_line(h: TopHolder) -> str:
    units = _fmt_units(h.units)
    delta = ""
    if h.units_changed is not None:
        sign = "+" if h.units_changed >= 0 else ""
        delta = f"  ({sign}{_fmt_units(h.units_changed)}"
        if h.pct_change_qoq is not None:
            delta += f", {sign}{h.pct_change_qoq:.1f}% Q-o-Q"
        delta += ")"
    val = f" — ${h.value_usd/1e9:.1f}B" if (h.value_usd and h.value_usd > 1e9) else (
        f" — ${h.value_usd/1e6:.0f}M" if h.value_usd else ""
    )
    return f"- **{h.name}** — {units} shares{delta}{val}"


def _fmt_units(u) -> str:
    if u is None:
        return "?"
    abs_u = abs(u)
    if abs_u >= 1e9:
        return f"{u/1e9:.2f}B"
    if abs_u >= 1e6:
        return f"{u/1e6:.1f}M"
    if abs_u >= 1e3:
        return f"{u/1e3:.0f}K"
    return f"{u:.0f}"
