"""Render DebateJudgment as readable markdown."""
from __future__ import annotations

from ..schemas import DebateJudgment


def render(j: DebateJudgment) -> str:
    winner_emoji = {"bull": "🟢", "bear": "🔴", "tie": "⚖"}.get(j.winner, "•")

    def _scoreline(label: str, scores) -> list[str]:
        return [
            f"### {label}",
            "",
            f"- Fundamental quality: {scores.fundamental_quality}/10",
            f"- News handling:       {scores.news_handling}/10",
            f"- Technical reasoning: {scores.technical_reasoning}/10",
            f"- Timing assessment:   {scores.timing_assessment}/10",
            f"- Rebuttal quality:    {scores.rebuttal_quality}/10",
            "",
        ]

    bull_total = (j.bull_scores.fundamental_quality + j.bull_scores.news_handling +
                   j.bull_scores.technical_reasoning + j.bull_scores.timing_assessment +
                   j.bull_scores.rebuttal_quality)
    bear_total = (j.bear_scores.fundamental_quality + j.bear_scores.news_handling +
                   j.bear_scores.technical_reasoning + j.bear_scores.timing_assessment +
                   j.bear_scores.rebuttal_quality)

    lines = [
        f"# Debate Judge — {j.symbol}",
        "",
        f"_Analysis date: {j.as_of_date}_",
        "",
        f"## {winner_emoji} **Winner: {j.winner.upper()}**",
        "",
        f"- **Final conviction:** {j.conviction_score}/10",
        f"- **Bull total score:** {bull_total}/50",
        f"- **Bear total score:** {bear_total}/50",
        "",
        "## Scoring",
        "",
    ]
    lines += _scoreline("Bull case", j.bull_scores)
    lines += _scoreline("Bear case", j.bear_scores)

    lines += [
        "## Deciding Factor",
        "",
        f"> {j.deciding_factor}",
        "",
        "## Synthesis",
        "",
        j.synthesis,
        "",
        "---",
        "",
        "_Generated by the Debate Judge (Claude Sonnet)._",
        "",
    ]
    return "\n".join(lines)
