"""Render MacroRegimeReport as markdown."""
from __future__ import annotations

from ..schemas import MacroRegimeReport


def render(r: MacroRegimeReport) -> str:
    lines = [
        f"# Macro Regime — {r.symbol}",
        "",
        f"_Analysis date: {r.as_of_date}_",
        "",
        f"**Market regime:** {r.market_regime}",
        f"**Market tide:** {r.market_tide_signal}",
        f"**Ticker alignment:** {r.ticker_alignment} (regime risk {r.regime_risk_score}/10)",
        "",
        "## Sector rotation",
        "",
    ]
    if r.ticker_sector:
        lines.append(f"- **{r.symbol} sector:** {r.ticker_sector} "
                     f"({r.sector_relative_strength})")
    if r.leading_sectors:
        lines.append(f"- **Leading:** {', '.join(r.leading_sectors)}")
    if r.lagging_sectors:
        lines.append(f"- **Lagging:** {', '.join(r.lagging_sectors)}")

    if r.upcoming_macro_events:
        lines += ["", "## Upcoming macro events", ""]
        for e in r.upcoming_macro_events:
            lines.append(f"- {e}")
        if r.next_high_impact_event_days is not None:
            lines.append(f"")
            lines.append(f"_Next high-impact event in {r.next_high_impact_event_days} days_")

    lines += [
        "",
        "## Summary",
        "",
        r.summary,
        "",
        "---",
        "",
        "_Generated by the Macro Regime agent (Gemini Flash) — Unusual Whales market data._",
        "",
    ]
    return "\n".join(lines)
