"""Render MorningBriefing — the daily client-facing message."""
from __future__ import annotations

import re

from ..schemas import MorningBriefing


def render(b: MorningBriefing) -> str:
    lines = [
        f"# Morning Briefing — {b.as_of_date}",
        "",
        f"**{b.headline}**",
        "",
        "## Message to client",
        "",
        _as_blockquote(b.telegram_message),
        "",
        "---",
        "",
        "_Generated by the Morning Briefing Composer (Gemini Flash)._",
        "",
    ]
    return "\n".join(lines)


def _as_blockquote(text: str) -> str:
    """Render text as a single markdown blockquote — wraps naturally, preserves
    line breaks. Empty lines stay as `>` so the quote remains a single block.
    Defensively normalizes "sentence.NextSentence" → "sentence. NextSentence"
    and splits all-on-one-line LLM output into one sentence per line.
    """
    text = _normalize_paragraph(text)
    out_lines: list[str] = []
    for line in text.split("\n"):
        if line.strip():
            out_lines.append(f"> {line}")
        else:
            out_lines.append(">")
    return "\n".join(out_lines)


def _normalize_paragraph(text: str) -> str:
    # 1. Insert a space when an LLM glued sentences together ("trend.We" → "trend. We").
    text = re.sub(r"([.!?])([A-Z])", r"\1 \2", text)
    # 2. If the message has zero newlines, break on sentence boundaries so the
    #    blockquote reads as a list rather than one wall of text.
    if "\n" not in text.strip():
        text = re.sub(r"([.!?])\s+", r"\1\n", text)
    return text.strip()
