"""Render NewsReport as readable markdown."""
from __future__ import annotations

from ..schemas import NewsReport


def render(r: NewsReport) -> str:
    lines: list[str] = [
        f"# News Analyst — {r.symbol}",
        "",
        f"_Analysis date: {r.as_of_date}_",
        "",
        "## Scores",
        "",
        f"- **News risk:** {r.news_risk_score}/10",
        f"- **News opportunity:** {r.news_opportunity_score}/10",
        "",
        "## Signals",
        "",
        f"- **Analyst consensus direction:** {r.analyst_consensus_direction}",
        f"- **Institutional flow:** {r.institutional_flow_signal}",
        "",
    ]

    if r.critical_flags:
        lines += ["## Critical Flags", ""]
        for f in r.critical_flags:
            lines += [f"- **[{f.severity}/{f.type}]** {f.detail}"]
        lines += [""]

    if r.recent_catalysts:
        lines += ["## Recent Catalysts", ""]
        for c in r.recent_catalysts:
            lines += [f"- {c}"]
        lines += [""]

    if r.event_risk_next_7_days:
        lines += ["## Event Risk (Next 7 Days)", ""]
        for e in r.event_risk_next_7_days:
            date_part = f" ({e.date})" if e.date else ""
            lines += [f"- **[{e.severity}]**{date_part} {e.event}"]
        lines += [""]

    lines += [
        "## Summary",
        "",
        r.summary,
        "",
        "---",
        "",
        "_Generated by the News Analyst agent._",
        "",
    ]
    return "\n".join(lines)
