"""Render OptionsStructureReport as markdown."""
from __future__ import annotations

from ..schemas import OptionsStructureReport


def render(r: OptionsStructureReport) -> str:
    lines = [
        f"# Options Structure — {r.symbol}",
        "",
        f"_Analysis date: {r.as_of_date}_",
        "",
        f"**Dealer positioning:** {r.dealer_positioning}",
        f"**IV regime:** {r.iv_regime} ({r.iv_term_structure})",
        f"**Structural signal:** {r.structural_signal}",
        "",
        "## Price levels (dealer-driven)",
        "",
    ]
    if r.current_price is not None:
        lines.append(f"- **Current price:** ${r.current_price:.2f}")
    if r.gamma_flip_price is not None:
        lines.append(f"- **Gamma flip:** ${r.gamma_flip_price:.2f}")
    if r.call_wall_strike is not None:
        lines.append(f"- **Call wall (resistance):** ${r.call_wall_strike:.2f}")
    if r.put_wall_strike is not None:
        lines.append(f"- **Put wall (support):** ${r.put_wall_strike:.2f}")
    if r.max_pain_nearest_expiry is not None:
        lines.append(f"- **Max pain (nearest expiry):** ${r.max_pain_nearest_expiry:.2f}")
    if r.max_pain_30dte is not None:
        lines.append(f"- **Max pain (30 DTE):** ${r.max_pain_30dte:.2f}")

    lines += [
        "",
        "## Summary",
        "",
        r.summary,
        "",
        "---",
        "",
        "_Generated by the Options Structure agent (Gemini Flash) — Unusual Whales data._",
        "",
    ]
    return "\n".join(lines)
