"""Render PMDecision as readable markdown — the final verdict file."""
from __future__ import annotations

import re

from ..schemas import PMDecision


def render(d: PMDecision) -> str:
    decision_emoji = {"APPROVE": "✅", "RESIZE": "⚖", "REJECT": "✗"}.get(d.decision, "•")

    lines: list[str] = [
        f"# Portfolio Manager Verdict — {d.symbol}",
        "",
        f"_Analysis date: {d.as_of_date}_",
        "",
        f"## {decision_emoji} **Decision: {d.decision}**",
        "",
        f"- **Conviction:** {d.conviction_score}/10",
    ]

    # Dynamic, AI-decided risk plan (per-stock).
    if d.position_pct_of_fund is not None:
        lines.append(f"- **Position size:** {d.position_pct_of_fund:.1f}% of the fund")
        if d.sizing_rationale:
            lines.append(f"  - _{d.sizing_rationale}_")
    if d.stop_price is not None:
        stop_txt = f"- **Stop-loss:** ${d.stop_price:,.2f}"
        if d.stop_pct is not None:
            stop_txt += f" (−{d.stop_pct:.1f}%)"
        lines.append(stop_txt)
        if d.stop_rationale:
            lines.append(f"  - _{d.stop_rationale}_")
    if d.position_pct_of_fund is None:
        lines.append(f"- **Recommended size:** {d.recommended_size_pct}% of normal allocation")

    lines += [
        "",
        "## Investment Rationale",
        "",
        "### Why now",
        "",
        d.investment_rationale.why_now,
        "",
        "### What validates the signal",
        "",
        d.investment_rationale.what_validates_signal,
        "",
        "### Key risk and how we manage it",
        "",
        d.investment_rationale.key_risk_and_management,
        "",
        "## Exit Thesis",
        "",
        f"> {d.exit_thesis}",
        "",
    ]

    if d.monitoring_flags:
        lines += ["## Monitoring Flags", ""]
        for flag in d.monitoring_flags:
            lines += [f"- {flag}"]
        lines += [""]

    lines += [
        "## 📈 Stock view (Telegram message 1)",
        "",
        _as_blockquote(d.telegram_message),
        "",
    ]

    if d.telegram_portfolio_message:
        lines += [
            "## 💼 Portfolio-fit view (Telegram message 2)",
            "",
            "_How this stock would slot into the existing book — rotation guidance._",
            "",
            _as_blockquote(d.telegram_portfolio_message),
            "",
        ]

    lines += [
        "## Audit Note (internal)",
        "",
        f"> {d.audit_note}",
        "",
        "---",
        "",
        "_Generated by the Portfolio Manager / CIO (Claude Sonnet)._",
        "",
    ]
    return "\n".join(lines)


def _as_blockquote(text: str) -> str:
    """Render text as a single markdown blockquote — wraps naturally, preserves
    line breaks. Defensively normalizes "sentence.NextSentence" spacing and
    splits all-on-one-line LLM output into one sentence per line.
    """
    text = _normalize_paragraph(text)
    out_lines: list[str] = []
    for line in text.split("\n"):
        if line.strip():
            out_lines.append(f"> {line}")
        else:
            out_lines.append(">")
    return "\n".join(out_lines)


def _normalize_paragraph(text: str) -> str:
    text = re.sub(r"([.!?])([A-Z])", r"\1 \2", text)
    if "\n" not in text.strip():
        text = re.sub(r"([.!?])\s+", r"\1\n", text)
    return text.strip()
