"""Render PositionMonitorReport as readable markdown."""
from __future__ import annotations

from ..schemas import PositionMonitorReport


def render(r: PositionMonitorReport) -> str:
    lines = [
        f"# Position Monitor — {r.as_of_date}",
        "",
        f"## Portfolio observation",
        "",
        f"> {r.portfolio_observation}",
        "",
        "## Per-position review",
        "",
        "| Symbol | Action | Thesis | Momentum | Reason |",
        "|---|---|---|---|---|",
    ]
    for rev in r.reviews:
        action_badge = {
            "HOLD": "🟢 HOLD",
            "WATCH": "🟡 WATCH",
            "EXIT": "🔴 EXIT",
        }.get(rev.action, rev.action)
        # Inline-escape pipes in the reason field
        reason = rev.reason.replace("|", "\\|")
        lines.append(
            f"| **{rev.symbol}** | {action_badge} | {rev.thesis_status} "
            f"| {rev.momentum_status} | {reason} |"
        )

    lines += [
        "",
        "---",
        "",
        "_Generated by the Position Monitor (Gemini Pro, batch call)._",
        "",
    ]
    return "\n".join(lines)
