"""Render MarketRegime as readable markdown."""
from __future__ import annotations

from ..schemas import MarketRegime


def render(r: MarketRegime) -> str:
    emoji = {
        "BULL_TRENDING": "🟢",
        "BULL_CHOPPY": "🟢",
        "NEUTRAL": "⚪",
        "RISK_OFF": "🟡",
        "BEAR": "🔴",
    }.get(r.regime, "•")
    lines = [
        f"# Market Regime — {r.as_of_date}",
        "",
        f"## {emoji} **{r.regime}**",
        "",
        f"- **Confidence:** {r.regime_confidence}/10",
        f"- **New entries:** {r.new_entries_throttle}",
        f"- **Trailing stops:** {r.trailing_stops_adjustment}",
        f"- **Quant threshold bump:** +{r.score_threshold_bump:.2f}",
        "",
        "## Key Observation",
        "",
        f"> {r.key_observation}",
        "",
        "## Watch Today",
        "",
        f"> {r.watch_today}",
        "",
        "---",
        "",
        "_Generated by the Market Regime Detector (Gemini Pro)._",
        "",
    ]
    return "\n".join(lines)
