"""Render RiskManagerVerdict as readable markdown."""
from __future__ import annotations

from ..schemas import RiskManagerVerdict


def render(r: RiskManagerVerdict) -> str:
    emoji = {
        "CLEAR":       "✅",
        "REDUCE_SIZE": "⚠",
        "BLOCK":       "🚫",
    }.get(r.verdict, "•")

    lines = [
        f"# Risk Manager — {r.symbol}",
        "",
        f"_Analysis date: {r.as_of_date}_",
        "",
        f"## {emoji} **Verdict: {r.verdict}**",
        "",
        f"- **Recommended size:** {r.recommended_size_pct}%",
        f"- **Open positions:** {r.open_position_count}",
        f"- **Sector ({r.sector or '—'}):** "
        f"now {r.sector_concentration_now_pct:.2f}% → "
        f"after {r.sector_concentration_after_pct:.2f}%",
        f"- **Gross exposure now:** {r.gross_exposure_now_pct:.2f}%",
    ]
    if r.earnings_risk_days is not None:
        lines.append(f"- **Earnings risk:** {r.earnings_risk_days} days")
    lines.append("")

    if r.deterministic_block_reason:
        lines += [
            "## 🚫 Deterministic block",
            "",
            f"> {r.deterministic_block_reason}",
            "",
            "_No LLM call was made — this is a hard rule from the fund constitution._",
            "",
        ]

    if r.rules_triggered:
        lines += ["## Rules triggered", ""]
        for rule in r.rules_triggered:
            lines += [f"- `{rule}`"]
        lines += [""]

    lines += [
        "## Reasoning",
        "",
        r.reasoning,
        "",
        "---",
        "",
        "_Generated by the Risk Manager (Claude Sonnet + deterministic gates)._",
        "",
    ]
    return "\n".join(lines)
