"""Render TechnicalContext as readable markdown."""
from __future__ import annotations

from ..schemas import TechnicalContext


def render(t: TechnicalContext) -> str:
    lines = [
        f"# Technical Context — {t.symbol}",
        "",
        f"_Analysis date: {t.as_of_date}_",
        "",
        f"**Technical strength:** {t.technical_strength}/10",
        "",
        "## Read",
        "",
        f"- **Volume confirmation:** {t.volume_confirmation}",
        f"- **Sector alignment:** {t.sector_alignment}",
        f"- **Broader market supportive:** {'yes' if t.broader_market_supportive else 'no'}",
        "",
    ]
    if t.return_vs_sector_20d_pct is not None:
        lines.append(f"- **Return vs sector (20d):** {t.return_vs_sector_20d_pct:+.2f}%")
    if t.return_vs_spy_20d_pct is not None:
        lines.append(f"- **Return vs SPY (20d):** {t.return_vs_spy_20d_pct:+.2f}%")
    lines.append("")

    if t.warning_flags:
        lines += ["## Warning flags", ""]
        for f in t.warning_flags:
            lines += [f"- {f}"]
        lines += [""]

    lines += [
        "## Summary",
        "",
        t.summary,
        "",
        "---",
        "",
        "_Generated by the Technical Context agent (Gemini Flash)._",
        "",
    ]
    return "\n".join(lines)
