"""Weekly review pipeline — Agent 14, Friday after close.

Persists artifacts to ai_research/_weekly/{week_end}/14_weekly_review.md
and pushes the telegram_weekly_report via Telegram.
"""
from __future__ import annotations

import json
import logging
from datetime import date, timedelta
from typing import Any, Callable, Optional

from ..config import AI_RESEARCH_DIR
from .agents.weekly_reviewer import run_weekly_review
from .schemas import WeeklyReviewReport

log = logging.getLogger(__name__)


async def run_weekly_cycle(
    target_date: Optional[date] = None,
    progress: Optional[Callable[..., None]] = None,
) -> Optional[WeeklyReviewReport]:
    """Run a weekly review for the week ending `target_date` (defaults to today)."""
    today = target_date or date.today()
    # ISO week — Mon to Sun. The reviewer is run Friday after close, so
    # week_start = the Monday on or before today, week_end = today.
    week_start = today - timedelta(days=today.weekday())
    week_end = today

    def _step(stage: str, msg: str, **extra: Any) -> None:
        log.info("[weekly:%s] %s", stage, msg)
        if progress:
            try:
                progress(stage, msg, **extra)
            except Exception:  # noqa: BLE001
                pass

    _step("init", f"reviewing {week_start} → {week_end}")
    report = await run_weekly_review(week_start, week_end)
    if report is None:
        _step("done", "no activity — review skipped")
        return None

    _step("write", "persisting review artifact")
    _persist_artifacts(week_end, report)

    # Telegram push
    try:
        from .telegram import telegram as _telegram
        client = _telegram()
        if client.enabled and report.telegram_weekly_report:
            ok = await client.send_message(
                report.telegram_weekly_report,
                kind="weekly_review",
            )
            _step("notify", f"telegram {'sent' if ok else 'skipped'}")
    except Exception as e:  # noqa: BLE001
        _step("notify", f"telegram error: {e}")

    _step("done", f"grade={report.weekly_grade}, "
                   f"decisions={report.n_decisions}, "
                   f"closed={report.n_positions_closed}")
    return report


def _persist_artifacts(week_end: date, report: WeeklyReviewReport) -> None:
    folder = AI_RESEARCH_DIR / "_weekly" / week_end.isoformat()
    folder.mkdir(parents=True, exist_ok=True)

    # Markdown report
    md = _render_md(report)
    (folder / "14_weekly_review.md").write_text(md, encoding="utf-8")

    # Raw JSON dump
    (folder / "_raw.json").write_text(
        report.model_dump_json(indent=2),
        encoding="utf-8",
    )


def _render_md(r: WeeklyReviewReport) -> str:
    lines: list[str] = [
        f"# Weekly Review — {r.week_start} to {r.week_end}",
        "",
        f"## Grade: **{r.weekly_grade}**",
        "",
        f"> {r.grade_justification}",
        "",
        "## Activity",
        "",
        f"- **Decisions made:** {r.n_decisions}",
        f"- **Approved:** {r.n_approved}",
        f"- **Resized:** {r.n_resized}",
        f"- **Rejected:** {r.n_rejected}",
        f"- **Positions closed:** {r.n_positions_closed}",
        "",
    ]

    if r.accuracy_by_conviction:
        lines += ["## Accuracy by conviction", "",
                   "| Bucket | Trades | Win rate | Avg P&L |",
                   "|---|---|---|---|"]
        for b in r.accuracy_by_conviction:
            lines.append(f"| {b.label} | {b.n_trades} | {b.win_rate_pct:.1f}% | {b.avg_pnl_pct:+.2f}% |")
        lines.append("")

    if r.accuracy_by_sector:
        lines += ["## Accuracy by sector", "",
                   "| Sector | Trades | Win rate | Avg P&L |",
                   "|---|---|---|---|"]
        for b in r.accuracy_by_sector:
            lines.append(f"| {b.label} | {b.n_trades} | {b.win_rate_pct:.1f}% | {b.avg_pnl_pct:+.2f}% |")
        lines.append("")

    if r.top_lessons:
        lines += ["## Top lessons", ""]
        for l in r.top_lessons:
            lines.append(f"- {l}")
        lines.append("")

    lines += [
        "## Process observations",
        "",
        r.process_observations,
        "",
        "## Client report (Telegram draft)",
        "",
    ]
    for line in r.telegram_weekly_report.split("\n"):
        lines.append(f"> {line}" if line.strip() else ">")

    lines += [
        "",
        "---",
        "",
        "_Generated by the Weekly Performance Reviewer (Claude Sonnet)._",
        "",
    ]
    return "\n".join(lines)
